Adds prow job config
jetstack/puppet-module-tarmak pull request #12
Opened 2017-11-13 16:02 UTC by simonswine

2017-11-13 16:45 UTC, simonswine commented
/retest

2017-11-14 15:40 UTC, simonswine commented
/retest

2017-11-14 16:21 UTC, simonswine commented
/retest

2017-11-14 17:12 UTC, simonswine commented
/retest

2017-11-14 19:24 UTC, munnerz commented
/shrug

2017-11-16 09:07 UTC, simonswine commented
/retest

2017-11-16 10:16 UTC, simonswine commented
/retest

2017-11-16 10:20 UTC, simonswine commented
/test quick-verify

2017-11-16 12:38 UTC, simonswine commented
/test acceptance

2017-11-16 12:43 UTC, simonswine commented
/test acceptance-centos
/test acceptance-ubuntu

2017-11-16 13:33 UTC, simonswine commented
/test acceptance-centos
/test acceptance-ubuntu

2017-11-16 14:44 UTC, simonswine commented
/test acceptance-centos v1.8

2017-11-16 15:32 UTC, simonswine commented
/test all

2017-11-16 17:31 UTC, simonswine commented
/test acceptance-ubuntu v1.7

2017-11-16 17:32 UTC, simonswine commented
/test acceptance-centos v1.5
/test acceptance-centos v1.6

2017-11-17 12:41 UTC, simonswine commented
/test acceptance-ubuntu v1.7

2017-11-17 12:48 UTC, simonswine commented
@kragniz if you take a quick look, if that makes sense. 1.8 is expected to fail 🙂

2017-11-17 12:54 UTC, kragniz requested changes
typo, otherwise looks good

2017-11-17 12:54 UTC, kragniz commented on Makefile
> +acecptance: acceptance-1-7-centos
typo on `acecptance`

2017-11-17 14:11 UTC, simonswine commented
/unshrug

2017-11-17 14:15 UTC, simonswine commented on Makefile
> +acecptance: acceptance-1-7-centos
Good spot!

2017-11-17 14:16 UTC, simonswine commented
/test acceptance-ubuntu v1.7
/test acceptance-centos v1.6
/test acceptance-centos v1.5

2017-11-17 14:23 UTC, merged